telegram:
    bot:
        token:

logger:
    type: local # local | axiom

    axiom:
        token:
        dataset:

origins:
    - http://127.0.0.1:5173
    - http://localhost:5173

session:
    secret: secret
