version: "3.9"

services:
    db:
        image: postgres:alpine
        ports:
            - "${DB_PORT:-5432}:5432"
        environment:
            POSTGRES_USER: ${DB_USER:?DB_USER is not specified}
            POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is not specified}
            POSTGRES_DB: ${DB_NAME:?DB_NAME is not specified}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis-cache:
        image: redis:alpine
        restart: always
        ports:
            - "${REDIS_PORT:-6379}:6379"
        command: redis-server --requirepass ${REDIS_PASSWORD:?REDIS_PASSWORD is not specified} --save 300 10
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
    redis_data:
