version: '3.8'

services:
    redis-cache:
        image: redis:6.2.16-alpine
        ports:
            - '${REDIS_PORT:-6379}:6379'
        command: >
            --requirepass ${REDIS_PASSWORD:?REDIS_PASSWORD is not specified}
        volumes:
            - redis_data:/data

volumes:
    redis_data: {}
