binance:
    isTestnet: true
    api:
        key: 
        secret: 

bybit:
    isDemoTrading: true
    api:
        key: 
        secret: 

telegram:
    bot:
        token: 
    allowed-user-ids:
        - 

logger:
    type: local # local | axiom

    # if selected type axiom
    axiom:
        token: 
        dataset: 
